apiVersion: v1
kind: Secret
metadata:
  labels:
    app: prometheus
    chart: prometheus-8.8.0
    component: alertmanager
    heritage: Tiller
  name: alertmanager
type: Opaque
stringData:
  alertmanager.yml: |
    global: {}
    route:
      group_wait: 10s
      group_interval: 5m
      receiver: slack
      repeat_interval: 3h
      routes:
      - receiver: slack
        repeat_interval: 5d
        match:
          severity: notify
          frequency: low
    receivers:
    - name: slack
      slack_configs:
      - api_url: SLACK_WEBHOOK_URL
        send_resolved: true
        title: "{{ .CommonAnnotations.summary }}"
        text: "{{ .CommonAnnotations.description }}"
        title_link: https://prometheus.dockerflow.com/alerts
