ingress:
  enabled: true
  hosts:
  - grafana.dockerflow.com
  annotations:
    kubernetes.io/tls-acme: "true"
  tls:
  - hosts:
    - grafana.dockerflow.com
    secretName: letsencrypt-secret-grafana
resources:
  limits:
    cpu: 20m
    memory: 50Mi
  requests:
    cpu: 5m
    memory: 25Mi
persistence:
  enabled: true
  accessModes:
  - ReadWriteOnce
  size: 1Gi
datasources:
 datasources.yaml:
   apiVersion: 1
   datasources:
   - name: Prometheus
     type: prometheus
     url: http://prometheus-server
     access: proxy
     isDefault: true
