server:
  ingress:
    enabled: true
    hosts:
    - prometheus.dockerflow.com
    annotations:
      kubernetes.io/tls-acme: "true"
    tls:
    - hosts:
      - prometheus.dockerflow.com
      secretName: letsencrypt-secret-prometheus
  resources:
    limits:
      cpu: 100m
      memory: 2500Mi
    requests:
      cpu: 40m
      memory: 1500Mi
alertmanager:
  ingress:
    enabled: true
    hosts:
    - alertmanager.dockerflow.com
    annotations:
      kubernetes.io/tls-acme: "true"
    tls:
    - hosts:
      - alertmanager.dockerflow.com
      secretName: letsencrypt-secret-alertmanager
  resources:
    limits:
      cpu: 10m
      memory: 20Mi
    requests:
      cpu: 5m
      memory: 10Mi
  configFromSecret: alertmanager
kubeStateMetrics:
  resources:
    limits:
      cpu: 10m
      memory: 50Mi
    requests:
      cpu: 5m
      memory: 25Mi
nodeExporter:
  resources:
    limits:
      cpu: 10m
      memory: 20Mi
    requests:
      cpu: 5m
      memory: 10Mi
pushgateway:
  resources:
    limits:
      cpu: 10m
      memory: 20Mi
    requests:
      cpu: 5m
      memory: 10Mi
nodeExporter:
  image:
    tag: v0.17.0-rc.0
serverFiles:
  alerts:
    groups:
    - name: latency
      rules:
      - alert: AppTooSlow
        expr: sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{le="1", ingress!~"jenkins|prometheus-server|grafana"}[5m])) by (ingress) / sum(rate(nginx_ingress_controller_request_duration_seconds_count{ingress!~"jenkins|prometheus-server"}[5m])) by (ingress) < 0.95
        for: 15m
        labels:
          severity: notify
        annotations:
          summary: Application is too slow
          description: More then 5% of requests are slower than 1s
      - alert: AppTooSlowInternal
        expr: sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{le="2.5", ingress=~"jenkins|prometheus-server|grafana"}[5m])) by (ingress) / sum(rate(nginx_ingress_controller_request_duration_seconds_count{ingress=~"jenkins|prometheus-server"}[5m])) by (ingress) < 0.95
        for: 15m
        labels:
          severity: notify
        annotations:
          summary: Internal application is too slow
          description: More then 5% of requests are slower than 2.5s
      - alert: TooManyRequests
        expr: sum(rate(nginx_ingress_controller_requests[5m])) by (ingress) / sum(label_join(kube_deployment_status_replicas, "ingress", ",", "deployment")) by (ingress) > 10
        labels:
          severity: notify
        annotations:
          summary: Too many requests
          description: There is more than average of 1 requests per second per replica for at least one application
    - name: nodes
      rules:
      - alert: TooManyNodes
        expr: count(kube_node_info) > 5
        for: 15m
        labels:
          severity: notify
        annotations:
          summary: Cluster increased
          description: The number of the nodes in the cluster increased
      - alert: TooFewNodes
        expr: count(kube_node_info) < 3
        for: 15m
        labels:
          severity: notify
        annotations:
          summary: Cluster decreased
          description: The number of the nodes in the cluster decreased
    - name: errors
      rules:
      - alert: TooManyErrors
        expr: sum(rate(nginx_ingress_controller_requests{status=~"5.."}[5m])) by (ingress) / sum(rate(nginx_ingress_controller_requests[5m])) by (ingress) > 0.05
        labels:
          severity: error
        annotations:
          summary: Too many errors
          description: At least one application produced more then 5% of error responses
    - name: pods
      rules:
      - alert: ProblematicPods
        expr: sum(kube_pod_status_phase{phase=~"Failed|Unknown|Pending"}) by (phase) > 0
        for: 15m
        labels:
          severity: notify
        annotations:
          summary: Problems with Pods
          description: At least one Pod is in a problematic phase
      - alert: OldPods
        expr: (time() - kube_pod_start_time{namespace!="kube-system"}) > (60 * 60 * 24 * 90)
        labels:
          severity: notify
          frequency: low
        annotations:
          summary: Old Pods
          description: At least one Pod has not been updated to more than 90 days
      - alert: ReservedMemTooLow
        expr: sum(label_join(container_memory_usage_bytes{namespace!="kube-system", namespace!="ingress-nginx", container_name!=""}, "pod", ",", "pod_name")) by (pod) / sum(kube_pod_container_resource_requests_memory_bytes{namespace!="kube-system"}) by (pod) > 1.5
        for: 1h
        labels:
          severity: notify
          frequency: low
        annotations:
          summary: Reserved memory is too low
          description: At least one Pod uses much more memory than it reserved
      - alert: ReservedMemTooHigh
        expr: sum(label_join(container_memory_usage_bytes{namespace!="kube-system", namespace!="ingress-nginx", container_name!=""}, "pod", ",", "pod_name")) by (pod) / sum(kube_pod_container_resource_requests_memory_bytes{namespace!="kube-system"}) by (pod) < 0.5 and sum(kube_pod_container_resource_requests_memory_bytes{namespace!="kube-system"}) by (pod) > 5.25e+06
        for: 6h
        labels:
          severity: notify
          frequency: low
        annotations:
          summary: Reserved memory is too high
          description: At least one Pod uses much less memory than it reserved
      - alert: ReservedCPUTooLow
        expr: sum(label_join(rate(container_cpu_usage_seconds_total{namespace!="kube-system", container_name!="", namespace!="ingress-nginx", pod_name!=""}[5m]), "pod", ",", "pod_name")) by (pod) / sum(kube_pod_container_resource_requests_cpu_cores{namespace!="kube-system"}) by (pod) > 1.5
        for: 1h
        labels:
          severity: notify
          frequency: low
        annotations:
          summary: Reserved CPU is too low
          description: At least one Pod uses much more CPU than it reserved
      - alert: ReservedCPUTooHigh
        expr: sum(label_join(rate(container_cpu_usage_seconds_total{namespace!="kube-system", pod_name!=""}[5m]), "pod", ",", "pod_name")) by (pod) / sum(kube_pod_container_resource_requests_cpu_cores{namespace!="kube-system", namespace!="ingress-nginx"}) by (pod) < 0.5 and sum(kube_pod_container_resource_requests_cpu_cores{namespace!="kube-system", namespace!="ingress-nginx"}) by (pod) > 0.005
        for: 6h
        labels:
          severity: notify
          frequency: low
        annotations:
          summary: Reserved CPU is too high
          description: At least one Pod uses much less CPU than it reserved
      - alert: MemoryAtTheLimit
        expr: sum(label_join(container_memory_usage_bytes{namespace!="kube-system", container_name!=""}, "pod", ",", "pod_name")) by (pod) / sum(kube_pod_container_resource_limits_memory_bytes{namespace!="kube-system"}) by (pod) > 0.8
        for: 1h
        labels:
          severity: notify
          frequency: low
        annotations:
          summary: Memory usage is almost at the limit
          description: At least one Pod uses memory that is close it its limit

